services:

  user-service:
    image: user-service:latest
    build:
      context: .
      dockerfile: user-service/Dockerfile        
    environment:
      - HOST_IP=0.0.0.0
    expose:
      - "5001"
       
  product-service:
    image: product-service:latest
    build:
      context: .
      dockerfile: product-service/Dockerfile
    environment:
      - HOST_IP=0.0.0.0
    expose:
      - "5002"

  order-service:
    image: order-service:latest
    build:
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      - HOST_IP=0.0.0.0
    expose:
      - "5003"

  nginx:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"  # ONLY keep ports exposed on Nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - user-service
      - product-service
      - order-service


