{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudshop-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Enable path rewriting adjustments to normalize endpoint queries smoothly
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          # Route traffic hitting /users directly to user-service
          - path: /users/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 5001

          # Route traffic hitting /products directly to product-service
          - path: /products/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-service
                port:
                  number: 5002

          # Route traffic hitting /orders directly to order-service
          - path: /orders/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-service
                port:
                  number: 5003

          # Fallback catch-all path: Route root traffic directly to your Frontend service UI
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
{{- end }}
