apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - localhost:9090

      - job_name: "frontend"
        static_configs:
          - targets:
              - frontend.production.svc.cluster.local:9113

      - job_name: "user-service"

        metrics_path: /metrics
        static_configs:
          - targets:
              - user-service.production.svc.cluster.local:5001

      - job_name: "product-service"

        metrics_path: /metrics
        static_configs:
          - targets:
              - product-service.production.svc.cluster.local:5002

      - job_name: "order_service"
        
        metrics_path: /metrics
        static_configs:
          - targets:
              - order-service.production.svc.cluster.local:5003
