server {
    listen 80;

    # Route to User Service
    location /users {
        proxy_pass http://user-service:5001/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route to Product Service
    location /products {
        proxy_pass http://product-service:5002/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route to Order Service
    location /orders {
        proxy_pass http://order-service:5003/orders;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route to User Service Health
    location /health/users {
        proxy_pass http://user-service:5001/health;
    } 

    # Route to Product Service Health
    location /health/products {
        proxy_pass http://product-service:5002/health;
    }

    # Route to Order Service Health
    location /health/orders {
        proxy_pass http://order-service:5003/health;
    }

  }
