# Global configurations for the microservices stack
global:
  registry: "shapherd777" # Replace with your actual Docker Hub username
  imageTag: "latest"     # This will be dynamically overridden by our GitHub Actions pipeline short-SHA

# User Service Configuration
userService:
  replicaCount: 2
  imageName: "user-service"
  internalPort: 5001
  env:
    HOST_IP: "0.0.0.0"

# Product Service Configuration
productService:
  replicaCount: 2
  imageName: "product-service"
  internalPort: 5002
  env:
    HOST_IP: "0.0.0.0"

# Order Service Configuration
orderService:
  replicaCount: 2
  imageName: "order-service"
  internalPort: 5003
  env:
    HOST_IP: "0.0.0.0"

# Frontend service configuration 
frontend:
  replicaCount: 1
  imageName: frontned
  internalPort: 80

ingress:
  enabled: true
  className: "nginx"
  host: "cloudshop.local"


