global:
  registry: "shepherd777"
  imageTag: "latest"

userService:
  replicaCount: 2
  imageName: "user-service"
  internalPort: 5001
  env:
    HOST_IP: "0.0.0.0"

userService:
  replicaCount: 2
  imageName: "product-service"
  internalPort: 5002
  env:
    HOST_IP: "0.0.0.0"

userService:
  replicaCount: 2
  imageName: "order-service"
  internalPort: 5003
  env:
    HOST_IP: "0.0.0.0"
  
